apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
  namespace: demo
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /media/sda1/psql
    server: 192.168.0.102
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: db-pvc
    namespace: demo
