apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
  namespace: demo
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /home/pi/nfs
    server: 192.168.1.2
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: db-pvc
    namespace: demo