basePath: /api
host: mortis-grimreaper.ddns.net
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: Remake of my previous attampted on creating API with Node.js
  license:
    name: MIT
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Gin API
  version: "1.0"
paths:
  /info:
    get: {}
swagger: "2.0"
